import {
  registerService,
  loginService,
  refreshTokenService,
} from "../services/auth.js";

export const register = async (req, res) => {
  try {
    const user = await registerService(req.body);

    res.cookie("accessToken", user.accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production", // true in production (HTTPS)
      sameSite: "lax",
      maxAge: 15 * 60 * 1000, // 15 min
    });

    res.cookie("refreshToken", user.refreshToken, {
      httpOnly: true,
      secure: false,
      sameSite: "lax",
      maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
    });

    res.status(201).json({
      message: "User registered successfully",
      userId: user._id,
    });
  } catch (error) {
    if (error.message === "USER_EXISTS") {
      return res.status(409).json({ message: "User already exists" });
    }
    res.status(500).json({ message: "Registration failed" });
  }
};

export const login = async (req, res) => {
  try {
    const user = await loginService(req.body);

    res.cookie("accessToken", user.accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production", // true in production (HTTPS)
      sameSite: "lax",
      maxAge: 15 * 60 * 1000, // 15 min
    });

    res.cookie("refreshToken", user.refreshToken, {
      httpOnly: true,
      secure: false,
      sameSite: "lax",
      maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
    });

    // 🔹 token is already generated by middleware
    res.json({
      message: "Login successful",
      user: user.user,
    });
  } catch (error) {
    if (error.message === "INVALID_CREDENTIALS") {
      return res.status(401).json({ message: "Invalid Id or password" });
    }
    console.log(error)
    res.status(500).json({ message: "Login failed" });
  }
};

export const refreshToken = async (req, res) => {
  try {
    const refreshToken = req.cookies.refreshToken;
    const user = await refreshTokenService(refreshToken);

    res.cookie("accessToken", user.accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",// true in production (HTTPS)
      sameSite: "lax",
      maxAge: 15 * 60 * 1000, // 15 min
    });

    res.json({
      message: "Token Refreshed",
    });
  } catch {
    res.status(403).json({ message: "Invalid refresh token" });
  }
};
